apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db-deployment
  labels:
    app: airflow
spec:
  selector:
    matchLabels:
      app: airflow
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: airflow
        tier: backend
    spec:
      containers:
        - name: airflow-db
          image: mysql:8.0.16
          env:
            - name: MYSQL_DATABASE
              value: airflow_db
            - name: MYSQL_ROOT_USER
              value: airflow_user
            - name: MYSQL_ROOT_PASSWORD
              value: airflow_password
          ports:
            - containerPort: 3306             
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-db-service
  labels:
    app: airflow
    tier: backend
spec:
  selector:
    app: airflow
    tier: backend
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
