apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  labels:
    app: airflow
spec:
  selector:
    matchLabels:
      app: airflow
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: airflow
        tier: frontend
    spec:
      containers:
        - name: airflow
          image: puckel/docker-airflow
          env:
            - name: LOAD_EX
              value: '1'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-frontend-service
  labels:
    app: airflow
    tier: frontend
spec:
  selector:
    app: airflow
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
