apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    name: airflow
  type: NodePort
  ports:
    - name: port1
      port: 80
      targetPort: 8080
    - name: port2
      port: 5555
      targetPort: 5555
    - name: port3
      port: 8793
      targetPort: 8793
---
apiVersion: v1
kind: Pod
metadata:
  name: airflow
  labels:
    name: airflow
spec:
  containers:
    - name: airflow
      image: puckel/docker-airflow
