apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  selector:
    name: superset
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
---
apiVersion: v1
kind: Pod
metadata:
  name: superset
  labels: 
    name: superset
spec:
  containers:
    - name: superset
      image: amancevice/superset
